#!/usr/bin/env python3
"""Plot ROC curve + AUC for the embedded Isolation Forest model on the test set.

Reads:  embedded_phase/src/model_engine/results/if_test_scores.json
        Generated by:
            pe_model_engine_cli --save-scores \
                embedded_phase/src/model_engine/results/if_test_scores.json

Writes: embedded_phase/src/model_engine/results/roc_curve_embedded_test.svg
        embedded_phase/src/model_engine/results/roc_curve_embedded_test.png

Usage (from repo root):
    python3 embedded_phase/src/model_engine/plot_roc.py
    python3 embedded_phase/src/model_engine/plot_roc.py \\
        --scores embedded_phase/src/model_engine/results/if_test_scores.json \\
        --output-dir embedded_phase/src/model_engine/results/
"""

import argparse
import json
import os
import sys
from bisect import bisect_left


# ---------------------------------------------------------------------------
# ROC computation
# ---------------------------------------------------------------------------

def compute_roc_curve(benign_scores: list, malware_scores: list):
    """
    Compute ROC curve for an Isolation Forest scorer.

    Convention (sklearn / this engine):
        anomaly if score < threshold  →  lower score = more suspicious.
        FPR = fraction of benign files scored strictly below threshold.
        TPR = fraction of malware files scored strictly below threshold.

    Returns a list of (fpr, tpr) tuples sorted by FPR ascending.
    """
    n_benign = len(benign_scores)
    n_malware = len(malware_scores)
    if n_benign == 0 or n_malware == 0:
        raise ValueError("Both benign_scores and malware_scores must be non-empty.")

    # All unique score values become candidate thresholds, plus open sentinels
    all_unique = sorted(set(benign_scores) | set(malware_scores))
    sentinels = [all_unique[0] - 1.0, all_unique[-1] + 1.0]
    thresholds = [sentinels[0]] + all_unique + [sentinels[1]]

    benign_sorted = sorted(benign_scores)
    malware_sorted = sorted(malware_scores)

    points = []
    for t in thresholds:
        fp = bisect_left(benign_sorted, t)     # scores strictly < t
        tp = bisect_left(malware_sorted, t)
        fpr = fp / n_benign
        tpr = tp / n_malware
        points.append((fpr, tpr))

    # Sort ascending by FPR, then descending by TPR so duplicates keep the best
    points.sort(key=lambda p: (p[0], -p[1]))

    # Deduplicate: for each unique FPR keep the max TPR
    deduped: list = []
    i = 0
    while i < len(points):
        cur_fpr = points[i][0]
        j = i
        while j < len(points) and points[j][0] == cur_fpr:
            j += 1
        max_tpr = max(p[1] for p in points[i:j])
        deduped.append((cur_fpr, max_tpr))
        i = j

    return deduped


def compute_auc(roc_points: list) -> float:
    """Trapezoidal-rule area under the ROC curve."""
    auc = 0.0
    for i in range(1, len(roc_points)):
        dx = roc_points[i][0] - roc_points[i - 1][0]
        avg_y = (roc_points[i][1] + roc_points[i - 1][1]) / 2.0
        auc += dx * avg_y
    return auc


# ---------------------------------------------------------------------------
# Plotting
# ---------------------------------------------------------------------------

def plot_roc(roc_points: list, auc: float, operating_point, output_dir: str):
    """
    Draw the ROC curve with:
    - the full curve coloured by density
    - a star marker at the selected decision threshold (operating point)
    - AUC annotation in the legend
    - a dashed diagonal (random classifier)

    operating_point: (fpr, tpr) tuple or None
    Returns (svg_path, png_path) on success, or (None, None) if matplotlib missing.
    """
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.ticker as ticker
    except ImportError:
        print(
            "matplotlib not available — skipping plot.\n"
            "Install with:  pip install matplotlib",
            file=sys.stderr,
        )
        return None, None

    fprs = [p[0] for p in roc_points]
    tprs = [p[1] for p in roc_points]

    fig, ax = plt.subplots(figsize=(7, 6))

    # Main ROC curve
    ax.plot(
        fprs, tprs,
        color="#1f77b4", linewidth=2.5,
        label=f"Embedded IF  (ROC-AUC = {auc:.4f})",
        zorder=3,
    )

    # Operating-point marker
    if operating_point is not None:
        op_fpr, op_tpr = operating_point
        ax.scatter(
            [op_fpr], [op_tpr],
            marker="*", s=200, color="#d62728", zorder=5,
            label=f"Selected threshold  (FPR={op_fpr:.4f}, TPR={op_tpr:.4f})",
        )

    # Random-classifier diagonal
    ax.plot(
        [0, 1], [0, 1],
        color="#aaaaaa", linestyle="--", linewidth=1.0, label="Random",
        zorder=1,
    )

    ax.set_xlabel("False Positive Rate", fontsize=12)
    ax.set_ylabel("True Positive Rate", fontsize=12)
    ax.set_title("ROC Curve — Embedded Isolation Forest (Test Set)", fontsize=13)
    ax.legend(loc="lower right", fontsize=10)
    ax.set_xlim((-0.01, 1.01))
    ax.set_ylim((-0.01, 1.01))
    ax.xaxis.set_major_formatter(ticker.FormatStrFormatter("%.2f"))
    ax.yaxis.set_major_formatter(ticker.FormatStrFormatter("%.2f"))
    ax.grid(True, linestyle=":", linewidth=0.7, alpha=0.6)
    fig.tight_layout()

    svg_path = os.path.join(output_dir, "roc_curve_embedded_test.svg")
    png_path = os.path.join(output_dir, "roc_curve_embedded_test.png")
    fig.savefig(svg_path, format="svg")
    fig.savefig(png_path, format="png", dpi=150)
    plt.close(fig)
    return svg_path, png_path


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    default_scores = os.path.join(script_dir, "results", "if_test_scores.json")
    default_output = os.path.join(script_dir, "results")

    parser = argparse.ArgumentParser(
        description="Plot ROC + AUC for the embedded Isolation Forest on the test set."
    )
    parser.add_argument(
        "--scores",
        default=default_scores,
        metavar="PATH",
        help="Path to if_test_scores.json  (default: results/if_test_scores.json)",
    )
    parser.add_argument(
        "--output-dir",
        default=default_output,
        metavar="DIR",
        help="Directory for output SVG/PNG  (default: results/)",
    )
    args = parser.parse_args()

    # ------------------------------------------------------------------
    # Load scores
    # ------------------------------------------------------------------
    if not os.path.exists(args.scores):
        print(f"[error] Scores file not found: {args.scores}", file=sys.stderr)
        print("Generate it first:", file=sys.stderr)
        print(
            "  pe_model_engine_cli "
            "--save-scores embedded_phase/src/model_engine/results/if_test_scores.json",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(args.scores, "r") as fh:
        data = json.load(fh)

    benign_scores: list = data["benign_test_scores"]
    malware_scores: list = data["malware_test_scores"]
    threshold = data.get("threshold", None)

    print(
        f"Loaded  {len(benign_scores)} benign-test scores, "
        f"{len(malware_scores)} malware-test scores."
    )

    # ------------------------------------------------------------------
    # Compute ROC + AUC
    # ------------------------------------------------------------------
    roc_points = compute_roc_curve(benign_scores, malware_scores)
    auc = compute_auc(roc_points)
    print(f"ROC-AUC (trapezoidal): {auc:.6f}")

    # Operating point at the selected threshold
    operating_point = None
    if threshold is not None:
        fp = sum(1 for s in benign_scores if s < threshold)
        tp = sum(1 for s in malware_scores if s < threshold)
        op_fpr = fp / len(benign_scores) if benign_scores else 0.0
        op_tpr = tp / len(malware_scores) if malware_scores else 0.0
        operating_point = (op_fpr, op_tpr)
        print(
            f"Operating point  (threshold={threshold:.6f}): "
            f"FPR={op_fpr:.4f}  TPR={op_tpr:.4f}"
        )

    # ------------------------------------------------------------------
    # Plot
    # ------------------------------------------------------------------
    os.makedirs(args.output_dir, exist_ok=True)
    svg_path, png_path = plot_roc(roc_points, auc, operating_point, args.output_dir)

    if svg_path:
        print(f"Saved SVG : {svg_path}")
        print(f"Saved PNG : {png_path}")
    else:
        print("Plot skipped (matplotlib unavailable).")


if __name__ == "__main__":
    main()
