#pragma once

#ifndef EDR_PE_MAX_INPUT_FILE_BYTES
#define EDR_PE_MAX_INPUT_FILE_BYTES (128ULL * 1024ULL * 1024ULL)
#endif

#ifndef EDR_PE_MAX_WORKING_SET_BYTES
#define EDR_PE_MAX_WORKING_SET_BYTES (256ULL * 1024ULL * 1024ULL)
#endif

#ifndef EDR_PE_MIN_INPUT_FILE_BYTES
#define EDR_PE_MIN_INPUT_FILE_BYTES 512ULL
#endif

#ifndef EDR_PE_MAX_PATH_BYTES
#define EDR_PE_MAX_PATH_BYTES 4096ULL
#endif

#ifndef EDR_PE_MAX_CLI_FILES_PER_RUN
#define EDR_PE_MAX_CLI_FILES_PER_RUN 2048ULL
#endif

#ifndef EDR_PE_MAX_CLI_TOTAL_INPUT_BYTES
#define EDR_PE_MAX_CLI_TOTAL_INPUT_BYTES (2ULL * 1024ULL * 1024ULL * 1024ULL)
#endif

#ifndef EDR_PE_MAX_THREADS
#define EDR_PE_MAX_THREADS 1ULL
#endif

#ifndef EDR_PE_MAX_SECTIONS
#define EDR_PE_MAX_SECTIONS 10ULL
#endif

#ifndef EDR_PE_MAX_IMPORT_DLLS
#define EDR_PE_MAX_IMPORT_DLLS 512ULL
#endif

#ifndef EDR_PE_MAX_IMPORT_FUNCS_TOTAL
#define EDR_PE_MAX_IMPORT_FUNCS_TOTAL 8192ULL
#endif

#ifndef EDR_PE_MAX_HASHABLE_NAME_BYTES
#define EDR_PE_MAX_HASHABLE_NAME_BYTES 256ULL
#endif

#ifndef EDR_PE_MAX_HASH_UPDATES_PER_FILE
#define EDR_PE_MAX_HASH_UPDATES_PER_FILE 10000ULL
#endif

#ifndef EDR_PE_MAX_OVERLAY_ENTROPY_BYTES
#define EDR_PE_MAX_OVERLAY_ENTROPY_BYTES 8192ULL
#endif

#ifndef EDR_PE_MAX_SIGNATURES
#define EDR_PE_MAX_SIGNATURES 4ULL
#endif

#ifndef EDR_PE_MAX_CERTIFICATES_TOTAL
#define EDR_PE_MAX_CERTIFICATES_TOTAL 64ULL
#endif

#ifndef EDR_PE_MAX_DEBUG_ENTRIES
#define EDR_PE_MAX_DEBUG_ENTRIES 128ULL
#endif

#ifndef EDR_PE_MAX_RICH_ENTRIES
#define EDR_PE_MAX_RICH_ENTRIES 256ULL
#endif

#ifndef EDR_PE_MAX_DATA_DIRECTORIES
#define EDR_PE_MAX_DATA_DIRECTORIES 16ULL
#endif

#ifndef EDR_PE_MAX_ERROR_TEXT_BYTES
#define EDR_PE_MAX_ERROR_TEXT_BYTES 256ULL
#endif
